// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMSModels.Data;

#nullable disable

namespace OMSModels.Migrations
{
    [DbContext(typeof(OMSContext))]
    partial class OMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OMSModels.Models.Basket", b =>
                {
                    b.Property<int>("IdBasket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBasket"));

                    b.Property<int>("IdShopper")
                        .HasColumnType("int");

                    b.HasKey("IdBasket");

                    b.HasIndex("IdShopper");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("OMSModels.Models.BasketItem", b =>
                {
                    b.Property<int>("IdBasketItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBasketItem"));

                    b.Property<int>("IdBasket")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdBasketItem");

                    b.HasIndex("IdBasket");

                    b.HasIndex("IdProduct");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("OMSModels.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("IdProduct");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OMSModels.Models.Shopper", b =>
                {
                    b.Property<int>("IdShopper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdShopper"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdShopper");

                    b.ToTable("Shoppers");
                });

            modelBuilder.Entity("OMSModels.Models.Basket", b =>
                {
                    b.HasOne("OMSModels.Models.Shopper", "Shopper")
                        .WithMany("Baskets")
                        .HasForeignKey("IdShopper")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shopper");
                });

            modelBuilder.Entity("OMSModels.Models.BasketItem", b =>
                {
                    b.HasOne("OMSModels.Models.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("IdBasket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMSModels.Models.Product", "Product")
                        .WithMany("BasketItems")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OMSModels.Models.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("OMSModels.Models.Product", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("OMSModels.Models.Shopper", b =>
                {
                    b.Navigation("Baskets");
                });
#pragma warning restore 612, 618
        }
    }
}
